import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { ToastProvider } from '@/context/ToastContext';
import WomenSafetyChatbot from '@/components/WomenSafetyChatbot';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId="760616524479-p9c0m5gnjn462u1k6eeb8cnp5as2jktt.apps.googleusercontent.com">
          <ToastProvider>
            {children}
            <WomenSafetyChatbot />
          </ToastProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
